CREATE TABLE blog_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  title TEXT NOT NULL,
  excerpt TEXT,
  content TEXT,
  image TEXT,
  date TEXT,
  read_time TEXT,
  author TEXT,
  category TEXT,
  tags TEXT[],
  status TEXT DEFAULT 'draft'::TEXT NOT NULL,
  featured BOOLEAN DEFAULT FALSE NOT NULL,
  views INT DEFAULT 0 NOT NULL
);

ALTER TABLE blog_posts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public profiles are viewable by everyone."
  ON blog_posts FOR SELECT
  USING (TRUE);

CREATE POLICY "Users can insert their own profiles."
  ON blog_posts FOR INSERT
  WITH CHECK (auth.uid() = NULL); -- Adjust if you implement user authentication

CREATE POLICY "Users can update own profile."
  ON blog_posts FOR UPDATE
  USING (auth.uid() = NULL); -- Adjust if you implement user authentication

CREATE POLICY "Users can delete own profile."
  ON blog_posts FOR DELETE
  USING (auth.uid() = NULL); -- Adjust if you implement user authentication
